export const actionTypes = {
    SETLOCATION: 'SETLOCATION',
    SETSTARTDATE: 'SETSTARTDATE',
    SETSTARTFINISHDATE: 'SETSTARTFINISHDATE',
    SETFINISHDATE: 'SETFINISHDATE',
    FULLUPDATESTATE: 'FULLUPDATESTATE',
    SETTOTALCOST: 'SETTOTALCOST',
    DEFAULT: 'DEFAULT'
}