export const actionTypes = {
    GETBOOKINGDETAILS: 'USERS_GETBOOKINGDETAILS',
    SETSTARTDATE: 'USERS_SETSTARTDATE',
    SETSTARTFINISHDATE: 'USERS_SETSTARTFINISHDATE',
    SETTIMESTART: 'USERS_SETTIMESTART',
    SETDURATION: 'USERS_SETDURATION',
    CHANGESTARTFINISHTIME: 'USER_CHANGESTARTFINISHTIME',
    FULLUPDATESTATE: 'USER_FULLUPDATESTATE'

}