export const actionTypes = {
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USER_LOGIN_FAILURE',
    LOGOUT: 'USERS_LOGOUT',


    FORGOT_REQUEST: 'USER_FORGOT_REQUEST',
    FORGOT_SUCCESS: 'USER_FORGOT_SUCCESS',
    FORGOT_FAILURE: 'USER_FORGOT_FAILURE',

    RESET_REQUEST: 'USER_RESET_REQUEST',
    RESET_SUCCESS: 'USER_RESET_SUCCESS',
    RESET_FAILURE: 'USER_RESET_FAILURE',

    GETALL_REQUEST: 'USERS_GETALL_REQUEST',
    GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
    GETALL_FAILURE: 'USERS_GETALL_FAILURE',

    DELETE_REQUEST: 'USERS_DELETE_REQUEST',
    DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
    DELETE_FAILURE: 'USERS_DELETE_FAILURE',

}